'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5485
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Agregar48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Agregar48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Asignatura48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Asignatura48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Borrar48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Borrar48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Borrar48b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Borrar48b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Carrera48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carrera48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property carreras_grid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("carreras grid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property carreras_grid2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("carreras grid2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property carreras10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("carreras10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CD48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CD48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Disco48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disco48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Disponibilidad48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disponibilidad48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Docente48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Docente48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Docente48a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Docente48a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Docente48b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Docente48b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Editar48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Editar48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Grabar48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grabar48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Grabar48a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grabar48a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Horarios48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Horarios48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Modulo48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Modulo48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Procesos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Procesos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Salir48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Salir48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Salir48b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Salir48b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tablas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tablas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
